# numpy exercise

In [1]:
import numpy as np

## 1. Literal array definition

In [2]:
A = np.array([
    [1, 3, 5, 7],
    [2, 4, 6, 8],
    [3, 5, 7, 9]
])

A

array([[1, 3, 5, 7],
       [2, 4, 6, 8],
       [3, 5, 7, 9]])

In [3]:
b = np.array([1, 2, 3, 4])
b

array([1, 2, 3, 4])

## 2. Array dimensions

numpy.ndarray.**shape**  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.shape.html

In [4]:
# 2-D array
A.shape

(3, 4)

In [5]:
# dimensions unpacking
n, m = A.shape

print('rows:', n)
print('cols:', m)

rows: 3
cols: 4


In [6]:
# 1-D array
b.shape

(4,)

In [7]:
c = b.reshape(1, -1)
c

array([[1, 2, 3, 4]])

In [8]:
# 2-D array
c.shape

(1, 4)

**Recommendation: avoid using 1-D arrays where possible** due to complex matrix operations rules: result may be surprising/unpredictable
  
use numpy.**reshape** to transform them into 2-D  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html

2.1. Create matrix $C$ by reshaping vector $c$ into dimensions $2 \times 2$

In [9]:
C = c.reshape(2, 2)
C

array([[1, 2],
       [3, 4]])

## 3. Matrix indexing and slicing

See docs:  
https://docs.scipy.org/doc/numpy-1.10.0/user/basics.indexing.html

or find some easier tutorial

3.1. Select $A_{1, 2}$

In [10]:
A[1, 2]

6

3.2. Select second column of $A$

In [11]:
A[:, 1]

array([3, 4, 5])

3.3. Select first two columns of $A$

In [12]:
A[:, :2]

array([[1, 3],
       [2, 4],
       [3, 5]])

3.4. Select last row of $A$

In [13]:
A[-1, :]

array([3, 5, 7, 9])

3.5. Select 1st and 3rd columns of $A$

In [14]:
A[:, [0, 2]]

array([[1, 5],
       [2, 6],
       [3, 7]])

## 4. Matrix operations
4.1. Transpose matrices $A, c$: get $A^T, c^T$  

numpy.ndarray.**transpose**  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.transpose.html

numpy.ndarray.**T** (shortcut)  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.T.html

In [15]:
A.T

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7],
       [7, 8, 9]])

In [16]:
c.T

array([[1],
       [2],
       [3],
       [4]])

4.2. Multiply $A \cdot c^T$ (don't forget to transpose $c$ to make dimensions match)

numpy.**dot**  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html

In [17]:
np.dot(A, c.T)

array([[50],
       [60],
       [70]])

4.3. Multiply $A * D$ elementwise

numpy.**multiply**  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.multiply.html

Find shortcut for matrix elementwise multiplication!

In [18]:
D = np.array([
    [1, 2, 1, 2],
    [1, 2, 1, 2],
    [1, 2, 1, 2]
])

In [19]:
A * D

array([[ 1,  6,  5, 14],
       [ 2,  8,  6, 16],
       [ 3, 10,  7, 18]])

4.4. Add and subtract matrices: $A + D, A - D$  

numpy.**add**  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.add.html

numpy.**subtract**  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.subtract.html

Find shortcuts!

In [20]:
A + D

array([[ 2,  5,  6,  9],
       [ 3,  6,  7, 10],
       [ 4,  7,  8, 11]])

In [21]:
A - D

array([[0, 1, 4, 5],
       [1, 2, 5, 6],
       [2, 3, 6, 7]])

4.5. Divide $A$ by $D$ elementwise  

numpy.**divide**  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.divide.html  

Find shortcut!

In [22]:
A / D

array([[1. , 1.5, 5. , 3.5],
       [2. , 2. , 6. , 4. ],
       [3. , 2.5, 7. , 4.5]])

## 5. Broadcasting

See docs:  
https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html

In [23]:
# 1 is repeated 3 x 4 times to make dimensions match
A + 1

array([[ 2,  4,  6,  8],
       [ 3,  5,  7,  9],
       [ 4,  6,  8, 10]])

In [24]:
A * 2

array([[ 2,  6, 10, 14],
       [ 4,  8, 12, 16],
       [ 6, 10, 14, 18]])

In [25]:
A ** 2

array([[ 1,  9, 25, 49],
       [ 4, 16, 36, 64],
       [ 9, 25, 49, 81]])

In [26]:
# c is stacked 3 times to make dimensions match
A + c

array([[ 2,  5,  8, 11],
       [ 3,  6,  9, 12],
       [ 4,  7, 10, 13]])

## 6. Automated matrix creation

6.1. Generate $Z \in \mathbb{R}^{2 \times 4}$ matrix filled with zeros

numpy.**zeros**  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html

In [27]:
Z = np.zeros((2, 4))
Z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

6.2. Generate $U \in \mathbb{R}^{5 \times 4}$ matrix filled with uniformely distributed values in range $(-8, 12)$

numpy.random.**uniform**  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.uniform.html

In [28]:
U = np.random.uniform(-8, 13, size=(5, 4))
U

array([[ 9.32638464, -2.28037535, 11.52500123,  2.61395233],
       [-5.64069685, -5.01638789,  9.27682625,  5.48068506],
       [12.69674405,  4.57470296,  5.94087219,  9.8226265 ],
       [ 3.56982401,  8.12088055, -5.25428105, -1.05835858],
       [-2.8876045 ,  1.43793602, -7.79080094, -1.54320482]])

6.3. Generate $N \in \mathbb{R}^{8 \times 3}$ matrix filled with normally distributed values with $\mu = 0$ and $\sigma = 5$

numpy.random.**normal**  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.normal.html

In [29]:
N = np.random.normal(0, 5, size=(8, 3))
N

array([[ 2.33896855,  4.88836148,  5.41803873],
       [ 0.46847047, -5.38651234,  7.56720497],
       [ 6.66559494, -5.06074021, -3.83626542],
       [-3.4529348 , -1.24649882, -3.05479161],
       [-0.32125499, -2.25778619, -6.14986186],
       [ 3.94320484,  2.90625063, -1.64250846],
       [-2.89972123,  1.07113882, -1.37884805],
       [-5.15579059, -2.6162144 ,  6.63962677]])

## 7. Matrix aggregate functions

7.1. Find mean, min and max values in $U$

numpy.**mean**  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html

numpy.ndarray.**min**  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.min.html

numpy.ndarray.**max**  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.max.html

In [30]:
np.mean(U)

2.6457362895360044

In [31]:
np.min(U)

-7.790800943853318

In [32]:
np.max(U)

12.696744050582446

7.2. Find mean and standard deviation for each column of $N$

numpy.**std**  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.std.html

In [33]:
N.mean(0)

array([ 0.19831715, -0.96275013,  0.44532438])

In [34]:
N.std(0)

array([3.74785179, 3.43140184, 4.94449705])

7.3. Find sum of all elements of $U$, also all row-wise and column-wise sums

numpy.**sum**  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.sum.html

In [35]:
U.sum()

52.914725790720084

In [36]:
U.sum(1)

array([ 21.18496284,   4.10042656,  33.0349457 ,   5.37806494,
       -10.78367425])

In [37]:
U.sum(0)

array([17.06465135,  6.83675628, 13.69761767, 15.31570049])

## 8. Other helpful functions

8.1. Create matrix $S$:
$S_{i, j}=
\begin{cases}
    1, & \text{if $N_{i, j} \ge 0$},\\
    -1, & \text{if $N_{i, j} < 0$}.
\end{cases}
$

numpy.**where**  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.where.html

In [38]:
S = np.where(N >= 0, 1, -1)
S

array([[ 1,  1,  1],
       [ 1, -1,  1],
       [ 1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1],
       [ 1,  1, -1],
       [-1,  1, -1],
       [-1, -1,  1]])